language: c

notifications:
  email: false
  
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz
  - tar xf arduino-1.8.10-linux64.tar.xz
  - sudo mv arduino-1.8.10 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/MPU925X

script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/AdvancedI2C/AdvancedI2C.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/BasicI2C/BasicI2C.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/BasicSPI/BasicSPI.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/InterruptSPI/InterruptSPI.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/WOMI2C/WOMI2C.ino